thorvald_001:
  topological_map: "data_collection"
  rgb_image_topics: 
   - "/thorvald_001/kinect2_top_right_camera/hd/image_color_rect"
  depth_image_topics:
   - "/thorvald_001/kinect2_top_right_camera/depth_registered/image_rect"
  camera_info_topics:
   - "/thorvald_001/kinect2_top_right_camera/hd/camera_info"
  nodes:
    - "r0-cstart"
    - "r0-c0"
    - "r0-c1"
    - "r0-c2"
    - "r0-c3"
    - "r0-c4"
    - "r0-c5"
    - "r0-c6"
    - "r0-c7"
    - "r0-c8"
    - "r0-c9"
    - "r0-c10"
    - "r0-c11"
    - "r0-c12"
    - "r0-c13"
    - "r0-c14"
    - "r0-c15"
    - "r0-c16"
    - "r0-c17"
    - "r0-c18"
    - "r0-c19"
    - "r0-c20"
    - "r0-cend"
  on_end:
    - "r0-cstart"