thorvald_001:
  topological_map: "data_collection"
  rgb_image_topics: 
   - "/thorvald_001/kinect2_top_right_camera/hd/image_color_rect"
  depth_image_topics:
   - "/thorvald_001/kinect2_top_right_camera/depth_registered/image_rect"
  camera_info_topics:
   - "/thorvald_001/kinect2_top_right_camera/hd/camera_info"
  nodes:
    - "r0-cstart"
    - "r0-c0"
    - "r0-c1"
    - "r0-c2"
    - "r0-c3"
    - "r0-c4"
    - "r0-c5"
    - "r0-c6"
    - "r0-c7"
    - "r0-c8"
    - "r0-c9"
    - "r0-c10"
    - "r0-c11"
    - "r0-c12"
    - "r0-c13"
    - "r0-c14"
    - "r0-c15"
    - "r0-c16"
    - "r0-c17"
    - "r0-c18"
    - "r0-c19"
    - "r0-c20"
    - "r0-cend"
  on_end:
    - "r0-cstart"
thorvald_002:
  topological_map: "data_collection"
  rgb_image_topics: 
   - "/thorvald_002/kinect2_top_left_camera/hd/image_color_rect"
   - "/thorvald_002/kinect2_top_right_camera/hd/image_color_rect"
  depth_image_topics:
   - "/thorvald_002/kinect2_top_left_camera/depth_registered/image_rect"
   - "/thorvald_002/kinect2_top_right_camera/depth_registered/image_rect"
  camera_info_topics:
   - "/thorvald_002/kinect2_top_left_camera/hd/camera_info"
   - "/thorvald_002/kinect2_top_right_camera/hd/camera_info"
  nodes:
    - "r1-cstart"
    - "r1-c0"
    - "r1-c1"
    - "r1-c2"
    - "r1-c3"
    - "r1-c4"
    - "r1-c5"
    - "r1-c6"
    - "r1-c7"
    - "r1-c8"
    - "r1-c9"
    - "r1-c10"
    - "r1-c11"
    - "r1-c12"
    - "r1-c13"
    - "r1-c14"
    - "r1-c15"
    - "r1-c16"
    - "r1-c17"
    - "r1-c18"
    - "r1-c19"
    - "r1-c20"
    - "r1-cend"
  on_end:
    - "r1-cstart"