thorvald_001:
  topological_map: "data_collection"
  rgb_image_topics: 
   - "/thorvald_001/kinect2_top_right_camera/hd/image_color_rect"
  depth_image_topics:
   - "/thorvald_001/kinect2_top_right_camera/depth_registered/image_rect"
  camera_info_topics:
   - "/thorvald_001/kinect2_top_right_camera/hd/camera_info"
  nodes:
    - "r0-cstart"
    - "r0-c0"
    - "r0-c1"
    - "r0-c2"
    - "r0-c3"
    - "r0-c4"
    - "r0-c5"
    - "r0-c6"
    - "r0-c7"
    - "r0-c8"
    - "r0-c9"
    - "r0-c10"
    - "r0-c11"
    - "r0-c12"
    - "r0-c13"
    - "r0-c14"
    - "r0-c15"
    - "r0-c16"
    - "r0-c17"
    - "r0-c18"
    - "r0-c19"
    - "r0-c20"
    - "r0-cend"
  on_end:
    - "r0-cstart"
# thorvald_002:
#   topological_map: "data_collection"
#   rgb_image_topics: 
#    - "/thorvald_002/kinect2_top_left_camera/hd/image_color_rect"
#    - "/thorvald_002/kinect2_top_right_camera/hd/image_color_rect"
#   depth_image_topics:
#    - "/thorvald_002/kinect2_top_left_camera/depth_registered/image_rect"
#    - "/thorvald_002/kinect2_top_right_camera/depth_registered/image_rect"
#   camera_info_topics:
#    - "/thorvald_002/kinect2_top_left_camera/hd/camera_info"
#    - "/thorvald_002/kinect2_top_right_camera/hd/camera_info"
#   nodes:
#     - "r1-cstart"
#     - "r1-c0"
#     - "r1-c1"
#     - "r1-c2"
#     - "r1-c3"
#     - "r1-c4"
#     - "r1-c5"
#     - "r1-c6"
#     - "r1-c7"
#     - "r1-c8"
#     - "r1-c9"
#     - "r1-c10"
#     - "r1-c11"
#     - "r1-c12"
#     - "r1-c13"
#     - "r1-c14"
#     - "r1-c15"
#     - "r1-c16"
#     - "r1-c17"
#     - "r1-c18"
#     - "r1-c19"
#     - "r1-c20"
#     - "r1-cend"
#   on_end:
#     - "r1-cstart"
# thorvald_003:
#   topological_map: "data_collection"
#   rgb_image_topics: 
#    - "/thorvald_003/kinect2_top_left_camera/hd/image_color_rect"
#    - "/thorvald_003/kinect2_top_right_camera/hd/image_color_rect"
#   depth_image_topics:
#    - "/thorvald_003/kinect2_top_left_camera/depth_registered/image_rect"
#    - "/thorvald_003/kinect2_top_right_camera/depth_registered/image_rect"
#   camera_info_topics:
#    - "/thorvald_003/kinect2_top_left_camera/hd/camera_info"
#    - "/thorvald_003/kinect2_top_right_camera/hd/camera_info"
#   nodes:
#     - "r2-cstart"
#     - "r2-c0"
#     - "r2-c1"
#     - "r2-c2"
#     - "r2-c3"
#     - "r2-c4"
#     - "r2-c5"
#     - "r2-c6"
#     - "r2-c7"
#     - "r2-c8"
#     - "r2-c9"
#     - "r2-c10"
#     - "r2-c11"
#     - "r2-c12"
#     - "r2-c13"
#     - "r2-c14"
#     - "r2-c15"
#     - "r2-c16"
#     - "r2-c17"
#     - "r2-c18"
#     - "r2-c19"
#     - "r2-c20"
#     - "r2-cend"
#   on_end:
#     - "r2-cstart"
# thorvald_004:
#   topological_map: "data_collection"
#   rgb_image_topics: 
#    - "/thorvald_004/kinect2_top_left_camera/hd/image_color_rect"
#    - "/thorvald_004/kinect2_top_right_camera/hd/image_color_rect"
#   depth_image_topics:
#    - "/thorvald_004/kinect2_top_left_camera/depth_registered/image_rect"
#    - "/thorvald_004/kinect2_top_right_camera/depth_registered/image_rect"
#   camera_info_topics:
#    - "/thorvald_004/kinect2_top_left_camera/hd/camera_info"
#    - "/thorvald_004/kinect2_top_right_camera/hd/camera_info"
#   nodes:
#     - "r3-cstart"
#     - "r3-c0"
#     - "r3-c1"
#     - "r3-c2"
#     - "r3-c3"
#     - "r3-c4"
#     - "r3-c5"
#     - "r3-c6"
#     - "r3-c7"
#     - "r3-c8"
#     - "r3-c9"
#     - "r3-c10"
#     - "r3-c11"
#     - "r3-c12"
#     - "r3-c13"
#     - "r3-c14"
#     - "r3-c15"
#     - "r3-c16"
#     - "r3-c17"
#     - "r3-c18"
#     - "r3-c19"
#     - "r3-c20"
#     - "r3-cend"
#   on_end:
#     - "r3-cstart"
# thorvald_005:
#   topological_map: "data_collection"
#   rgb_image_topics: 
#    - "/thorvald_005/kinect2_top_left_camera/hd/image_color_rect"
#    - "/thorvald_005/kinect2_top_right_camera/hd/image_color_rect"
#   depth_image_topics:
#    - "/thorvald_005/kinect2_top_left_camera/depth_registered/image_rect"
#    - "/thorvald_005/kinect2_top_right_camera/depth_registered/image_rect"
#   camera_info_topics:
#    - "/thorvald_005/kinect2_top_left_camera/hd/camera_info"
#    - "/thorvald_005/kinect2_top_right_camera/hd/camera_info"
#   nodes:
#     - "r4-cstart"
#     - "r4-c0"
#     - "r4-c1"
#     - "r4-c2"
#     - "r4-c3"
#     - "r4-c4"
#     - "r4-c5"
#     - "r4-c6"
#     - "r4-c7"
#     - "r4-c8"
#     - "r4-c9"
#     - "r4-c10"
#     - "r4-c11"
#     - "r4-c12"
#     - "r4-c13"
#     - "r4-c14"
#     - "r4-c15"
#     - "r4-c16"
#     - "r4-c17"
#     - "r4-c18"
#     - "r4-c19"
#     - "r4-c20"
#     - "r4-cend"
#   on_end:
#     - "r4-cstart"
# thorvald_006:
#   topological_map: "data_collection"
#   rgb_image_topics: 
#    - "/thorvald_006/kinect2_top_left_camera/hd/image_color_rect"
#    - "/thorvald_006/kinect2_top_right_camera/hd/image_color_rect"
#   depth_image_topics:
#    - "/thorvald_006/kinect2_top_left_camera/depth_registered/image_rect"
#    - "/thorvald_006/kinect2_top_right_camera/depth_registered/image_rect"
#   camera_info_topics:
#    - "/thorvald_006/kinect2_top_left_camera/hd/camera_info"
#    - "/thorvald_006/kinect2_top_right_camera/hd/camera_info"
#   nodes:
#     - "r5-cstart"
#     - "r5-c0"
#     - "r5-c1"
#     - "r5-c2"
#     - "r5-c3"
#     - "r5-c4"
#     - "r5-c5"
#     - "r5-c6"
#     - "r5-c7"
#     - "r5-c8"
#     - "r5-c9"
#     - "r5-c10"
#     - "r5-c11"
#     - "r5-c12"
#     - "r5-c13"
#     - "r5-c14"
#     - "r5-c15"
#     - "r5-c16"
#     - "r5-c17"
#     - "r5-c18"
#     - "r5-c19"
#     - "r5-c20"
#     - "r5-cend"
#   on_end:
#     - "r5-cstart"
# thorvald_007:
#   topological_map: "data_collection"
#   rgb_image_topics: 
#    - "/thorvald_007/kinect2_top_left_camera/hd/image_color_rect"
#   depth_image_topics:
#    - "/thorvald_007/kinect2_top_left_camera/depth_registered/image_rect"
#   camera_info_topics:
#    - "/thorvald_007/kinect2_top_left_camera/hd/camera_info"
#   nodes:
#     - "r6-cstart"
#     - "r6-c0"
#     - "r6-c1"
#     - "r6-c2"
#     - "r6-c3"
#     - "r6-c4"
#     - "r6-c5"
#     - "r6-c6"
#     - "r6-c7"
#     - "r6-c8"
#     - "r6-c9"
#     - "r6-c10"
#     - "r6-c11"
#     - "r6-c12"
#     - "r6-c13"
#     - "r6-c14"
#     - "r6-c15"
#     - "r6-c16"
#     - "r6-c17"
#     - "r6-c18"
#     - "r6-c19"
#     - "r6-c20"
#     - "r6-cend"
#   on_end:
#     - "r6-cstart"